function expTable = table_expData( expData, stats )

% Remove suffix: "Ruleswitching" from expID
expID = char({expData.sub_dir}');
expID = expID(:,1:10); %or regexp... 


% Generate Summary Table for all Experiments

rowDist = ones(numel(expData),1);
%'Index',mat2cell((1:numel(expData))',rowDist),...
S = struct(...
    'Experiment_ID',mat2cell(expID,rowDist),...
    'Strain',{expData.strain}',...
    'Virus',{expData.virus}',...
    'nTrials',mat2cell(stats.behavior.all.trialsCompleted.data,rowDist),...
    'nBlocks',mat2cell(stats.behavior.all.blocksCompleted.data,rowDist),...
    'nCells',  mat2cell(stats.imaging.all.totalCells.data,rowDist),...
    'nExcl',  mat2cell(stats.imaging.all.exclCells.data,rowDist)...
    );

expTable = struct2table(S);
expTable.Properties.RowNames = mat2cell(num2str((1:numel(expData))'),rowDist);
disp(expTable);

