function [ blocks ] = flex_getBlockData( sessionData, trialData )
% % getBlockData % %
%PURPOSE: Retrieve block and trial data specific to the flexibility task.
%AUTHORS: MJ Siniscalchi 161212.
%         modified by   AC Kwan 170515
%                       MJ Siniscalchi 190701
%
%INPUT ARGUMENTS
%   sessionData:    Structure generated by flex_getSessionData().
%   trialData:      Structure generated by flex_getSessionData().
%
%OUTPUT VARIABLES
%   blocks:         Fields: 
%                   {firstTrial, nTrials, ...
%                   hit, err_p, err_o, miss, ...
%                   contingType, ruleType}. 

%CODES FROM NBS PRESENTATION
[STIM, RESP, OUTCOME, EVENT] = getPresentationCodes(sessionData.presCodeSet);

%GET nSWITCHES, BLOCKTYPES, nTRIALS
nTrials = sessionData.nTrials;

idx.sound = find(ismember(trialData.cue,[STIM.sound_UPSWEEP,STIM.sound_DNSWEEP])); %Rule inferred from cue code  
idx.actionL = find(ismember(trialData.cue,[STIM.left_UPSWEEP,STIM.left_DNSWEEP])); 
idx.actionR = find(ismember(trialData.cue,[STIM.right_UPSWEEP,STIM.right_DNSWEEP])); 

lastTrial.sound = idx.sound(diff([idx.sound; nTrials+1])~=1);   %Last trial pre-switch for each block, by rule
lastTrial.actionL = idx.actionL(diff([idx.actionL; nTrials+1])~=1);
lastTrial.actionR = idx.actionR(diff([idx.actionR; nTrials+1])~=1);

switchTrial = sort(cell2mat(struct2cell(lastTrial)))+1;         %Index of lastTrial + 1 is index of firstTrial in new block
blocks.firstTrial = [1; switchTrial]; %First trial of each block

% Block Type
blocks.type = cell(numel(blocks.firstTrial),1);
blocks.type(ismember(blocks.firstTrial,idx.sound)) = {'Sound'};
blocks.type(ismember(blocks.firstTrial,idx.actionL)) = {'ActionL'};
blocks.type(ismember(blocks.firstTrial,idx.actionR)) = {'ActionR'};

blocks.nTrials = diff([blocks.firstTrial; nTrials+1]); %Number trials in each block
end