function blocks = getPerfData( trialData, trials, blocks )
%%% getPerfData()
%PURPOSE: Retrieve block and trial data specific to the flexibility task,
%         particularly those known only after running flex_getTrialMasks
%AUTHOSR: MJ Siniscalchi 161212.
%         modified by AC Kwan 170515
%
%INPUT ARGUMENTS
%   blocks:     structure generated by calling flex_getBlockData().
%   trials:     structure generated by calling flex_getTrialMasks().
%
%OUTPUT VARIABLES
%   blocks:         Fields: 
%                   {firstTrial, nTrials, ...
%                   hit, err_p, err_o, miss, ...
%                   contingType, ruleType}. 
%---------------------------------------------------------------------------------------------------
nTrials = sum(blocks.nTrials);

%% Gross Performance Statistics for each Block
fields = {'hit' 'pErr' 'oErr' 'miss'};
for i = 1:numel(fields)
    idx = trials.(fields{i}); %Trial index
    edges = [blocks.firstTrial; nTrials];
    counts = histcounts(find(idx),edges); %Count number of each trial type in each block
    blocks.(fields{i}) = counts; 
end

%% Median Reaction Time for each Block
for i = 1:numel(blocks.type)
    idx = (blocks.firstTrial(i) : blocks.firstTrial(i)+blocks.nTrials(i)-1); %Indices for all trials in i-th block
    blocks.RT(i) = nanmedian(trialData.reactionTimes(idx));
end
