%%% analyze_RuleSwitchingSession
%
%PURPOSE: To analyze individual sessions from a two-choice auditory rule switching task.
%
%AUTHOR: MJ Siniscalchi, 190701
%
%TO DO LIST:
%   -Remove tons of extraneous code from getPresentationCodes.m
%
%--------------------------------------------------------------------------

clearvars;

%% Set paths

% Set paths to analysis code
[data_dir,~,~] = setPathList;
% Assign data directories and get experiment-spec parameters
[logfile,path] = uigetfile([data_dir '\*.log'],...
    'Select .LOG file generated by NBS Presentation');

%% Analyze behavior and generate figs

% Parse logfile
logData = parseLogfile(path,logfile);
% Get stimulus, response, and outcome data from each trial
[sessionData, trialData] = getSessionData(logData);
% Get data from each rule block
blocks = getBlockData(sessionData, trialData );
% Generate logical masks for specific trial types
trials = getTrialMasks(sessionData, trialData, blocks);
% Get performance data for each rule block (hitrate, persev error rate, etc.)
blocks = getPerfData( blocks, trials );

%Save processed data
mat_file = logfile(1:end-4);
save(fullfile(path, mat_file),...
    'logData','sessionData','trialData','blocks','trials');

%% Figures 

%Visualize raw behavioral data
time_range = [-2 5];
tlabel = [sessionData.subject{:},'--',sessionData.dateTime{1}];
fig = plot_flexBehByTrial(trialData,trials,tlabel,time_range);
savefig(fig,fullfile(path,['raw_beh_',mat_file]));
saveas(fig,fullfile(path,['raw_beh_',mat_file '.png']));
