function [ comparison, trialSpec ] = list_trialSpecs( analysisName, params )

switch analysisName
    case 'bootAvg'
        subsets = {...
            'choice_sound',...
            {'left' 'hit' 'sound'},...
            {'right' 'hit' 'sound'};... %Decode choice in Sound trials
            'choice_action',...
            {'left' 'hit' 'action'},...
            {'right' 'hit' 'action'};... %Decode choice in Action trials
            
            'prior_choice',...
            {'priorLeft' 'priorHit' 'sound'}...
            {'priorRight' 'priorHit' 'sound'};... %Decode prior choice in Sound trials
            'prior_choice_action',...
            {'priorLeft' 'priorHit' 'action'}...
            {'priorRight' 'priorHit' 'action'};... %Decode prior choice in Action trials
            
            'outcome',...
            {'hit','priorHit'},...
            {'err','priorHit'};... %Decode outcome
            'prior_outcome',...
            {'priorHit','hit'},...
            {'priorErr','hit'};... %Prior outcome
            
            'rule_SL',...
            {'sound' 'left' 'upsweep' 'last20'},... %Decode rule with cue/choice/outcome fixed
            {'actionL' 'left' 'upsweep' 'last20'};...
            'rule_SR',...
            {'sound' 'right' 'downsweep' 'last20'},...
            {'actionR' 'right' 'downsweep' 'last20'};...
            }; %Spec for each trial subset for comparison (conjunction of N fields from 'trials' structure.)
        
        comparison = subsets(:,1);
        trialSpec = subsets(:,2:3);
        
    case 'decode_single_units' %Should be same as bootAvg
       
end